- name: Install package
  hosts: local
  connection: local
  tasks:
  - name: Installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - zip
    - mysql